parse options of gridjobs

diff --git a/bin/gridjobs b/bin/gridjobs
--- a/bin/gridjobs
+++ b/bin/gridjobs
@@ -1,6 +1,6 @@
 #!/bin/sh
 ###################################################
-#     Copyright (C) 2011 Arnaud Malapert.
+#     Copyright (C) 2013 Arnaud Malapert (UNS CNRS).
 #
 #     This program is free software: you can redistribute it and/or modify                    
 #     it under the terms of the GNU General Public License as published by
@@ -16,10 +16,33 @@
 #     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ###################################################
 
+
+#--------------------------------------------------------------------
+# Setup Global Variables
+#--------------------------------------------------------------------
+
 PROG=`basename $0 .sh`
+ALGORITHMS=algorithms
+INSTANCES=instances
+RESULTS=results
+SOLVER=./solver.sh;
+
+ERRFILE=oar-stderr.log
+
+#Option arguments
+PATTERN='*.txt'
+RANDOMSEED=$$
+SUBMODE=2;
+
+
+
+#--------------------------------------------------------------------
+# Version and help messages
+#--------------------------------------------------------------------
+
 version() {
 cat <<EOF
-$PROG 0.1
+$PROG 0.2
      
 Copyright (C) 2011 Arnaud Malapert.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -28,67 +51,72 @@ EOF
 
 help() {
 cat <<EOF
-$PROG generates new jobs (shell script) for the batch server. 
-For each 'file' matching PATTERN in a subdirectory of BENCH, $PROG generates a script 'file.sh' which executes a single command CMD. 
-The target file is referenced in CMD by using '{}'. 
+$PROG generates new jobs for the batch scheduler OAR. $PROG operates in the current directory.
+For each solver configuration file in the flat directory $ALGORITHMS, and for each file matching the pattern in subdirectories of $INSTANCES, $PROG submits a new job based on the shell script $SOLVER.
 
-For further automatic analysis of the optimization results, we will assume that : 
-a) each schell script solves exactly one instance, 
-b) the standard output is formatted according to the rules specified in the documentation,
-c) The standard and error outputs are redirected to files with extension .o and .e respectivly.
+All error outputs are redirected to the file $ERRFILE.
+For each algorithm and each instance file, the standard output is redirected to a .o file in the directory $RESULTS.
 
-Usage: $PROG [OPTION]... BENCH PATTERN CMD
+Usage: $PROG [OPTION]... 
 
 Options:
- --help        display this help and exit
- --version     output version information and exit
+ -p 'PATTERN'     filename pattern for instances   
+ -s  SEED         random seed  
+ 
+ -l        serial submission on localhost
+ -g        grid submission with OAR
+ -d        only print submission with OAR (debug)
+
+ -h        display this help and exit
+ -v        output version information and exit
      
 Report bugs to <arnaud (dot) malapert (at) unice (dot) fr>."
 EOF
 }
 
-#--------------------------------------------------------------------
-# Setup Global Variables
-#--------------------------------------------------------------------
 
-ALGORITHMS=algorithms
-INSTANCES=instances
-RESULTS=results
-SOLVER=./solver.sh;
-
-ERRFILE=oar-stderr.log
-
-RANDOMSEED=$$
-
-PATTERN='*.txt'
 #--------------------------------------------------------------------
 # Test for prerequisites
 #--------------------------------------------------------------------
 
 
-if [ $# -eq 0 ] || [ $1 = "-h" ]; then
-    help
-    exit 0
-elif [ $1 = "-v" ]; then
-    version
-    exit 0
-# elif [ $# -lt 3 ] ; then
-#     help
-#     exit 1
-fi
 
+while getopts ":p:s:lgdhv" opt; do
+    case $opt in
+        p)
+            PATTERN=$OPTARG
+            ;;
+        s)
+            SEED=$OPTARG
+            ;;
+       l)
+            SUBMODE=1
+            ;;
+       g)
+            SUBMODE=2
+            ;;
+       d)
+            SUBMODE=3
+            ;;
+        h)
+            help 
+            exit 0
+            ;;
+        v)
+            version;
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
+done
 
-SUBT=1;
-
-# if [ $1 = "-s" ] || [ $1 = "--sequential" ] ; then
-#     SUBT=1;
-#     shift
-# elif [ $1 = "-p" ] || [ $1 = "--print" ] ; then
-#     SUBT=2;
-#     shift
-# else
-#     SUBT=0;
-# fi
 
 #--------------------------------------------------------------------
 # Do something
@@ -123,10 +151,10 @@ do
         OUTFILE=$RESULTS/${ADIR%.*}/$OUTFILE
         ##TODO print and simulation options
         OARCMD="oarsub --stderr $ERRFILE --stdout $OUTFILE -S \"$SOLVER $ALGOPATH $BENCHPATH $RANDOMSEED\""
-        case $SUBT in 
-            #serial execution
+        case $SUBMODE in 
+            #serial submission on localhost
             1) $SOLVER $ALGOPATH $BENCHPATH $RANDOMSEED > $OUTFILE 2> $ERRFILE;;
-            ## grid execution
+            ## OAR submission on a cluster
             2) $OARCMD;;
             ## debug mode (only print command)
             *) echo $OARCMD;;
